Test3.1/Models/Country.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using JCTools.GenericCrud.DataAnnotations;

namespace Test3._1.Models
{
    public class Country
    {
        [Key]
        [Crud(Visible = false)]
        public int Id
        {
            get;
            set;
        }

        [Required(ErrorMessage="RequiredField")]
        [Display(Name = "Name", Order = 1)]
        public string Name
        {
            get;
            set;
        }        
    }
}

Test3.1/Models/ErrorViewModel.cs
using System;

namespace Test3._1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Test3.1/Models/Genre.cs
using System.ComponentModel.DataAnnotations;
using JCTools.GenericCrud.DataAnnotations;

namespace Test3._1.Models
{
    public class Genre
    {
        [Key]
        [Crud(IsEditableKey = true)]
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Test3.1/Models/Movie.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using JCTools.GenericCrud.DataAnnotations;

namespace Test3._1.Models
{
    public class Movie
    {
        [Key]
        [Crud(Visible = false)]
        public int Id
        {
            get;
            set;
        }

        [Required(ErrorMessage="RequiredField")]
        [Display(Name = "Title", Order = 1)]
        public string Title
        {
            get;
            set;
        }
        [Display(Order = 2)]        
        public string Director
        {
            get;
            set;
        }

        [Display(Order = 4)]
        public int Year
        {
            get;
            set;
        }
        [Display(Order = 3)]  
        [Crud(UseCustomView = true)]      
        public int Country
        {
            get;
            set;
        }
    }
}

Test3.1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Test3._1.Models;

namespace Test3._1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStringLocalizer<HomeController> _localizer;
        private readonly IActionDescriptorCollectionProvider _actionDescriptorCollectionProvider;
        private readonly EndpointDataSource _endpointsDataSource;

        public HomeController(ILogger<HomeController> logger,
            IStringLocalizer<HomeController> localizer,
            IActionDescriptorCollectionProvider actionDescriptorCollectionProvider,
            EndpointDataSource endpointsDataSource
        )
        {
            _localizer = localizer;
            _actionDescriptorCollectionProvider = actionDescriptorCollectionProvider;
            _endpointsDataSource = endpointsDataSource;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet("routes/{controllerName?}")]
        public IActionResult GetRoutes(string controllerName)
        {
            var routes = _actionDescriptorCollectionProvider.ActionDescriptors.Items
            .Cast<ControllerActionDescriptor>()
            .Select(x => new
            {
                Action = x.ActionName,
                Controller = x.ControllerName,
                Name = x.AttributeRouteInfo?.Name,
                DisplayName = x.DisplayName,
                Template = x.AttributeRouteInfo?.Template,
                Method = x.MethodInfo.ToString(),
                RouteValues = x.RouteValues,
                Properties = x.Properties,
                ActionConstraints = x.ActionConstraints,
                Parameters = x.Parameters.Select(p => p.Name),
                BoundProperties = x.BoundProperties.Select(p => p.Name),
                FilterDescriptors = x.FilterDescriptors
            })
            .Where(x => string.IsNullOrWhiteSpace(controllerName) || x.Controller.Equals(controllerName))
            .ToList();
            return Content(Newtonsoft.Json.JsonConvert.SerializeObject(routes), "application/json");
        }

        [HttpGet("endpoints")]
        public IActionResult GetEndpoints()
        {
            var endpoints = _endpointsDataSource.Endpoints
                .Cast<RouteEndpoint>()
                .Select(x => new
                {
                    x.Order,
                    x.DisplayName,
                    x.RoutePattern,
                    Metadata = x.Metadata.Select(md =>
                    {
                        switch (md)
                        {
                            case PageRouteMetadata prm:
                                return (object)new
                                {
                                    prm.PageRoute,
                                    prm.RouteTemplate,
                                    Type = prm.GetType().Name
                                };
                            case PageActionDescriptor pad:
                                return (object)new
                                {
                                    pad.Id,
                                    pad.AreaName,
                                    pad.DisplayName,
                                    pad.ViewEnginePath,
                                    pad.RelativePath,
                                    Type = pad.GetType().Name
                                };
                            case RouteNameMetadata rnm:
                                return (object)new
                                {
                                    rnm.RouteName,
                                    Type = rnm.GetType().Name
                                };
                            case SuppressLinkGenerationMetadata slg:
                                return (object)new {
                                    slg.SuppressLinkGeneration,
                                    Type = slg.GetType().Name
                                };
                            default:
                                return (object)new{
                                    ToString = md.ToString(),
                                    Type = md.GetType().Name
                                };
                        }
                    })
                })
                .ToList();

            return Content(Newtonsoft.Json.JsonConvert.SerializeObject(endpoints), "application/json");
        }
    }
}

Test3.1/Controllers/MovieController.cs
using System;
using System.Linq;
using JCTools.GenericCrud.Controllers;
using JCTools.GenericCrud.DataAnnotations;
using JCTools.GenericCrud.Services;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Test3._1.Data;
using Test3._1.Models;

namespace Test3._1.Controllers
{
    [CrudConstraint(typeof(Movie))]
    public class MovieController : GenericController
    {
        public MovieController(
            IServiceProvider serviceProvider,
            IViewRenderService renderingService,
            ILoggerFactory loggerFactory
        )
            : base(serviceProvider, renderingService, loggerFactory, nameof(Models.Movie.Id))
        {
            // add your custom logic here
        }

        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            // Call the initialization of the Settings property
            base.InitSettings(filterContext);
            // Add your custom settings here, eg;
            Settings.UseModals = false;
            Settings.Subtitle = "All entities";
            ViewBag.Countries = (DbContext as Context).Countries.ToList();

            base.OnActionExecuting(filterContext);
        }
    }
}

Test3.1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Test3.1/Views/Movie/_DetailsCountry.cshtml
@using System.Collections.Generic;
@using System.Collections;
@using System.Linq;
@model Test3._1.Models.Movie

@{
    var country = (ViewBag.Countries as IEnumerable<Test3._1.Models.Country>)
            .FirstOrDefault(c => c.Id == Model.Country);
}
@(country?.Name ?? string.Empty)

Test3.1/Views/Movie/_EditCountry.cshtml
@model Test3._1.Models.Movie


<label class="col-md-2 text-right" asp-for="Country">@Localizer["Country"]</label>          
<div class="col-md-10"> 
    <select asp-for="Country">
        @foreach(var country in ViewBag.Countries)
        {
            <option value="@country.Id">@country.Name</option>
        }
    </select>                   
    <span asp-validation-for="Country" class="text-danger"></span>
</div>

Test3.1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test3._1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">        
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Test3._1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">@Localizer["Movie"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">@Localizer["Country"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">@Localizer["Genre"]</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Test3._1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>